#ifndef __DLSCREEN_BI__
#define __DLSCREEN_BI__

common shared sridx_hp as integer
common shared sridx_money as integer
common shared sridx_moniker as integer
common shared sridx_vp as integer
common shared sridx_tp as integer
common shared sridx_playfield as integer
common shared sridx_menu_area as integer
common shared sridx_dialog as integer
common shared sridx_npc_info as integer

declare sub screen_init()

#endif
