#ifndef __FACTION_BI__
#define __FACTION_BI__

const FACTION_MILITARY as integer = 0 
const FACTION_LOS_ZETAS as integer = 1
const FACTION_SINALOA as integer = 2
const FACTION_GULF as integer = 3
const FACTION_LA_FAMILIA as integer = 4
const FACTION_TIJUANA as integer = 5
const FACTION_KNIGHTS_TEMPLAR as integer = 8
const FACTION_BELTRAN_LEVYA as integer = 6
const FACTION_JUAREZ as integer = 7
const FACTION_CIVILIAN as integer = 9

#endif
